### PR TITLE
Update publish action

### PR DESCRIPTION
**Pull request by ryjones**
This needs the logic removed from build.yml (the actual publishing part, not the release creating part)

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
The logic in `build.yml` publishes packages for multiple platforms. We also don't support poetry (yet) although there's a PR starting that work.

**Comment by swcurran** [comment]
@andrewwhitehead — could you explain what your comment above means — what are the ramifications of what you are saying.  I think I’m reading it that we need to remove the multiple platforms and the poetry update needs to be completed?

**Comment by jamshale** [comment]
I don't think this publishing method requires poetry. It's just how it's configured in pypi and with github actions. In theory the pypi publishing can just be removed from the build.yml pipeline and it can publish after, leaving the other platforms unchanged.

I haven't had the chance to study this yet though, so I could be off.

**Comment by ryjones** [comment]
> I don't think this publishing method requires poetry. It's just how it's configured in pypi and with github actions. In theory the pypi publishing can just be removed from the build.yml pipeline and it can publish after, leaving the other platforms unchanged.
> 
> I haven't had the chance to study this yet though, so I could be off.

That was my thought - the completion of the other job could trigger the pypi job

**Comment by jamshale** [comment]
I'm working on another PR for this...

**Comment by swcurran** [comment]
@jamshale did a separate PR that handled the changes needed, and @andrewwhitehead updated the PyPi settings, so we should be good to go -- without this.  We'll see how the release goes...

**Pull request closed without merging**
